logger:
  name: "ichimoku"
  log_file: "logs/ichimoku.txt"
  level_name: "INFO"

exchange:
  name: "binance"
  api_key: "your_api_key"
  secret: "your_secret"
  sandbox: false
  enable_rate_limit: true

prompt:
  template: "ichimoku"
  max_positions: 3
  altcoin_leverage: 3
  BTC_ETH_leverage: 3
  history_span: 30

llm:
  model: "deepseek-chat"
  api_key: "llm_api_key"
  temperature: 1.0

backtest:
  start_time: "20250101-000000"
  end_time: "20250701-000000"
  initial_balance: 10000.0
  data_folder: "data"

strategy:
  name: ichimoku
  params: {}

trader:
  mode: "live"  # choices: ["backtest", "live"]
  timeframe: "4h"
  save_folder: "results/ichimoku"
  # symbols: ["BTC/USDT", "ETH/USDT"]
  symbols: ["BTC/USDT", "ETH/USDT", "SOL/USDT", "SUI/USDT"]
  # symbols: ["BTC/USDT", "ETH/USDT", "SOL/USDT", "BNB/USDT", "DOGE/USDT", "ADA/USDT", "AAVE/USDT", "SUI/USDT", "1000PEPE/USDT"]

indicators:
  "1h":
  - name: "EMA"
    params:
      timeperiod: 9
    display_name: "EMA9"

  - name: "EMA"
    params:
      timeperiod: 21
    display_name: "EMA21"

  - name: "EMA"
    params:
      timeperiod: 50
    display_name: "EMA50"

  "4h":
  - name: "heikinashi"
    params: {}
    display_name:
    - "ha_open"
    - "ha_high"
    - "ha_low"
    - "ha_close"

  - name: "ATR"
    params:
      timeperiod: 14
    display_name: "ATR14"

  - name: "ADX"
    params:
      timeperiod: 14
    display_name: "ADX14"

  - name: "MACD"
    params:
      fastperiod: 12
      slowperiod: 26
      signalperiod: 14
    display_name:
    - "MACD"
    - "MACD_signal"
    - "MACD_hist"

  - name: "RSI"
    params:
      timeperiod: 14
    display_name: "RSI14"

  - name: "BBANDS"
    params:
      timeperiod: 20
    display_name:
    - "BBANDS_upper"
    - "BBANDS_middle"
    - "BBANDS_lower"

  - name: "VOLSMA"
    params:
      timeperiod: 20
    display_name: "VOL_MA20"

  "1d":
  - name: "ichimoku"
    params:
      conversion_line_period: 20
      base_line_period: 60
      lagging_span: 120
      displacement: 30
      use_heikinashi: true
    display_name:
    - "TenkanSen"
    - "KijunSen"
    - "SenkouSpanA"
    - "SenkouSpanB"
